services:
  pymc-repeater:
    image: pymc-repeater:local
    build:
      context: .
      dockerfile: dockerfile
      args:
        PUID: ${PUID:-15888}
        PGID: ${PGID:-15888}
        GPIO_GID: ${GPIO_GID:-986}
        SPI_GID: ${SPI_GID:-989}
