services:
  pymc-repeater:
    build:
      context: .
      dockerfile: dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        GPIO_GID: ${GPIO_GID:-986}
        SPI_GID: ${SPI_GID:-989}
    container_name: pymc-repeater
    restart: unless-stopped
    ports:
      - 8000:8000
    devices:
      # SPI DEVICES (Your path may differ)
      - /dev/spidev0.0
      - /dev/gpiochip0
      # USB DEVICES (Your path may differ)
      - /dev/bus/usb/002:/dev/bus/usb/002
    # SPI DEVICES PERMISSIONS
    cap_add:
      - SYS_RAWIO
    # USB DEVICSE PERMISSIONS
    group_add:
      - "${GPIO_GID:-986}"
      - "${SPI_GID:-989}"
      - plugdev
    volumes:
      - ./config:/etc/pymc_repeater
      - ./data:/var/lib/pymc_repeater
