services:
  openhop-repeater:
    image: ${PYMC_REPEATER_IMAGE:-pymcdev/openhop-repeater:main}
    container_name: openhop-repeater
    restart: unless-stopped
    ports:
      - 8000:8000
    devices:
      # SPI DEVICES (Your path may differ)
      - /dev/spidev0.0
      - /dev/gpiochip0
      # USB DEVICES (Your path may differ)
      - /dev/bus/usb/002:/dev/bus/usb/002
    # SPI DEVICES PERMISSIONS
    cap_add:
      - SYS_RAWIO
    # USB DEVICE PERMISSIONS
    group_add:
      - "${DIALOUT_GID:-20}"
      - "${GPIO_GID:-986}"
      - "${SPI_GID:-989}"
      - plugdev
    volumes:
      - ${PYMC_CONFIG_VOLUME:-openhop-repeater-config}:/etc/openhop_repeater
      - ${PYMC_DATA_VOLUME:-openhop-repeater-data}:/var/lib/openhop_repeater

volumes:
  openhop-repeater-config:
  openhop-repeater-data:
