services:
  pymc-repeater:
    image: ${PYMC_REPEATER_IMAGE:-pymcdev/pymc-repeater:main}
    container_name: pymc-repeater
    restart: unless-stopped
    ports:
      - 8000:8000
    devices:
      # SPI DEVICES (Your path may differ)
      - /dev/spidev0.0
      - /dev/gpiochip0
      # USB DEVICES (Your path may differ)
      - /dev/bus/usb/002:/dev/bus/usb/002
    # SPI DEVICES PERMISSIONS
    cap_add:
      - SYS_RAWIO
    # USB DEVICE PERMISSIONS
    group_add:
      - "${GPIO_GID:-986}"
      - "${SPI_GID:-989}"
      - plugdev
    volumes:
      - ${PYMC_CONFIG_VOLUME:-pymc-repeater-config}:/etc/pymc_repeater
      - ${PYMC_DATA_VOLUME:-pymc-repeater-data}:/var/lib/pymc_repeater

volumes:
  pymc-repeater-config:
  pymc-repeater-data:
